name: travel
description: A new Flutter project.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  file_picker: ^5.2.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.12.0
  flutter_svg: ^2.0.2
  form_field_validator: ^1.1.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl: ^0.18.0
  lottie: ^2.2.0
  permission_handler: ^10.2.0
  rename: ^2.1.1
  share_plus: ^6.3.1
  shared_preferences: ^2.0.16
  syncfusion_flutter_pdfviewer: ^20.4.54
  unicons: ^2.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
